In [1]:
import numpy as np #importing numpy this way allows us to refer  to numpy as np

In [2]:
#creating numpy arrays
#new arrays can be made in several ways
#we can take an existing list and convert it to a numpy array
mylist = [1.,2.,3.,4.]
mynparray = np.array(mylist)

In [3]:
mynparray

array([ 1.,  2.,  3.,  4.])

In [4]:
#we can initialize and array(of any dimension) of all ones or all zeroes
#with ones() and zeros() functions
one_vector = np.ones(4)
print one_vector #using print removes the array portion

[ 1.  1.  1.  1.]


In [5]:
zero_vector = np.zeros(5)
print zero_vector

[ 0.  0.  0.  0.  0.]


In [6]:
one2Darray = np.ones((2,4)) #an 2D array with 2 rows and 4 columns

In [7]:
print one2Darray

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [8]:
#we can also initialize an empty array which will be filled with values
#this is the fastest way to initialize a fixed-size numpy array 
#however one must ensure that one replaces all the values
empty_vector = np.empty(5)
print empty_vector

[ 0.  0.  0.  0.  0.]


In [9]:
#accessing an array is straight forward. For vectors you access 
#the index by referring to it inside the square brackets
mynparray[2]

3.0

In [10]:
#2D aarrays are accessed similarly referring to the row and column index s
#separated by a comma
my_matrix = np.array([[1,2,3],[4,5,6]])
print my_matrix

[[1 2 3]
 [4 5 6]]


In [11]:
print my_matrix[1,2]

6


In [12]:
#sequences of indices can be accessed using ':' for example
print my_matrix[0:2,2]

[3 6]


In [13]:
print my_matrix[0:1,1]

[2]


In [14]:
print my_matrix[0:2] #recall 0:2 is [0,1]

[[1 2 3]
 [4 5 6]]


In [16]:
print my_matrix[:,2] #check how does this exactly work

[3 6]


In [17]:
print my_matrix[0,0:3]

[1 2 3]


In [18]:
#passing a list of indices
fib_indices = np.array([1,1,2,3])
random_vector = np.random.random(10) #10 random numbers betweebn 0 and 1


In [19]:
print random_vector

[ 0.9091631   0.99046321  0.54617464  0.07523616  0.39163824  0.8449602
  0.25229677  0.56044551  0.13316742  0.26985573]


In [21]:
print random_vector[fib_indices]

[ 0.99046321  0.99046321  0.54617464  0.07523616]


In [22]:
#can also use true/false to select values
my_vector = np.array([1,2,3,4])
select_index = np.array([True, False, True, False])
print my_vector[select_index]

[1 3]


In [23]:
#for 2D arrays we can select specific columns and specific rows. passing ':' sleects all rows and columns

In [24]:
select_cols = np.array([True, False, True]) #1st and 3rd column
select_rows = np.array([False, True]) #2nd row
print my_matrix[select_rows,:] #just 2nd row but all columns

[[4 5 6]]


In [26]:
print my_matrix[:,select_cols] #all rows and just the 1st and 3rd columns

[[1 3]
 [4 6]]


In [27]:
#operations on arrays are operated elementwise
my_array = np.array([1.,2.,3.,4.])
print my_array * my_array

[  1.   4.   9.  16.]


In [28]:
print my_array ** 2

[  1.   4.   9.  16.]


In [29]:
print my_array - np.ones(4)

[ 0.  1.  2.  3.]


In [30]:
print my_array + np.ones(4)

[ 2.  3.  4.  5.]


In [31]:
print my_array / 3

[ 0.33333333  0.66666667  1.          1.33333333]


In [32]:
print my_array / np.array([2.,3.,4.,5.])

[ 0.5         0.66666667  0.75        0.8       ]


In [33]:
#computing the sum and the average
print np.sum(my_array
            )

10.0


In [34]:
print np.average(my_array)

2.5


In [35]:
print np.sum(my_array)/len(my_array)

2.5


In [36]:
#the dot product which is multiplying them elementwise and adding them
array1 = np.array([1.,2.,3.,4.])
array2 = np.array([2.,3.,4.,5.])
print np.dot(array1, array2)

40.0


In [37]:
print np.sum(array1*array2)

40.0


In [38]:
#euclidean length or magnitude of the vector is the sum of the 
#squares of the components
array1_mag = np.sqrt(np.dot(array1,array1))

In [39]:
print array1_mag

5.47722557505


In [40]:
print np.sqrt(np.sum(array1*array1))

5.47722557505


In [41]:
#using the 2D array
my_features = np.array([[1.,2.],[3.,4.],[5.,6.],[7.,8.]])
print my_features

[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]
 [ 7.  8.]]


In [42]:
my_weights = np.array([0.4,0.5])
print my_weights

[ 0.4  0.5]


In [43]:
my_predictions = np.dot(my_features, my_weights) #note that the weights are on the right

In [44]:
print my_predictions #which has 4 elements since my_features has 4 rows 

[ 1.4  3.2  5.   6.8]


In [45]:
#if you have a vector with the same number of elements as the matrix has rows you can left multiply them
my_matrix = my_features
my_array = np.array([0.3,0.4,0.5,0.6])

In [46]:
print np.dot(my_array,my_matrix) #which has 2 elements because my_marix has 2 columns

[  8.2  10. ]


In [47]:
#multiplying matrices
matrix_1 = np.array([[1.,2.,3.],[4.,5.,6.]])
print matrix_1

[[ 1.  2.  3.]
 [ 4.  5.  6.]]


In [48]:
matrix_2 = np.array([[1.,2.],[3.,4.],[5.,6.]])
print matrix_2

[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]]


In [49]:
print np.dot(matrix_1, matrix_2)

[[ 22.  28.]
 [ 49.  64.]]
